name: Deploy to Root Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: env

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          echo "SSH_HOST='${{ vars.SSH_ROOT_HOST }}'"
          echo "SSH_PORT='${{ vars.SSH_ROOT_PORT }}'"
          mkdir -p ~/.ssh
          echo "${{ vars.SSH_ROOT_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          if [ -z "${{ vars.SSH_ROOT_PORT }}" ]; then
            ssh-keyscan -H ${{ vars.SSH_ROOT_HOST }} >> ~/.ssh/known_hosts
          else
            ssh-keyscan -H -p ${{ vars.SSH_ROOT_PORT }} ${{ vars.SSH_ROOT_HOST }} >> ~/.ssh/known_hosts
          fi

      - name: Copy files to server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ vars.SSH_ROOT_HOST }}
          username: root
          key: ${{ vars.SSH_ROOT_KEY }}
          port: ${{ vars.SSH_ROOT_PORT }}
          source: |
            docker-compose.yml
            .env
            internal/db/migrations
          target: /root/app

      - name: Deploy with docker-compose
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ vars.SSH_ROOT_HOST }}
          username: root
          key: ${{ vars.SSH_ROOT_KEY }}
          port: ${{ vars.SSH_ROOT_PORT }}
          script: |
            cd /root/app
            docker compose pull
            docker compose up -d --build
