name: Deploy to Root Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: env

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_ROOT_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p ${{ secrets.SSH_ROOT_PORT }} ${{ secrets.SSH_ROOT_HOST }} >> ~/.ssh/known_hosts

      - name: Copy files to server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_ROOT_HOST }}
          username: root
          key: ${{ secrets.SSH_ROOT_KEY }}
          port: ${{ secrets.SSH_ROOT_PORT }}
          source: |
            docker-compose.yml
            .env
            internal/db/migrations
          target: /root/app

      - name: Deploy with docker-compose
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_ROOT_HOST }}
          username: root
          key: ${{ secrets.SSH_ROOT_KEY }}
          port: ${{ secrets.SSH_ROOT_PORT }}
          script: |
            cd /root/app
            docker compose pull
            docker compose up -d --build
