name: Test and Deploy to Root Server

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Go Tests in Docker
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run tests with docker-compose
        run: |
         docker compose -f docker-compose.yml --profile test up --build --abort-on-container-exit tests
         docker compose down -v

  deploy:
    name: Deploy to Root Server
    runs-on: ubuntu-latest
    needs: test  
    environment: env

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client
          echo "SSH_HOST='${{ secrets.SSH_ROOT_HOST }}'"
          echo "SSH_PORT='${{ secrets.SSH_ROOT_PORT }}'"
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_ROOT_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          if [ -z "${{ secrets.SSH_ROOT_PORT }}" ]; then
            ssh-keyscan -H ${{ secrets.SSH_ROOT_HOST }} >> ~/.ssh/known_hosts
          else
            ssh-keyscan -H -p ${{ secrets.SSH_ROOT_PORT }} ${{ secrets.SSH_ROOT_HOST }} >> ~/.ssh/known_hosts
          fi

      - name: Deploy via Git pull on server
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_ROOT_HOST }}
          username: root
          key: ${{ secrets.SSH_ROOT_KEY }}
          port: ${{ secrets.SSH_ROOT_PORT }}
          script: |
            set -e
            docker compose version || docker-compose version
            if [ ! -d /root/app ]; then
              git clone https://github.com/haranton/online_shop_Golang.git /root/app
            else
              cd /root/app
              git pull
            fi      
            cd /root/app

            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
            docker compose down
            docker compose pull
            docker compose up -d --build
